# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: GitCode 首页
    url: "https://gitcode.com/"
    weight: 10
  - name: 帮助文档
    url: docs/
    weight: 20
  # - name: 博客
  #   url: blog/
  #   weight: 30
  - name: API 文档
    url: docs/api/
    weight: 40
  - name: 社区支持
    url: community/
    weight: 50

sidebar:
  - identifier: more
    name: 还需要更多帮助?
    params:
      type: separator
    weight: 1
  - identifier: community
    name: "社区支持"
    pageRef: "/community"
    weight: 2
  - identifier: hugoDocs
    name: "反馈中心 ↗"
    url: "https://gitcode.com/Gitcode-offical-team/GitCode-Docs/issues"
    weight: 3
